openapi: 3.0.0
info:
  title: SQL Chat App
  version: 1.0.0
servers:
  - url: https://sql-talk-app-api.hipolito.dev/
    description: Development server
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
tags:
  - name: Users
  - name: Auth
  - name: Chats
  - name: Messages
paths:
  /api/users:
    post:
      tags:
        - Users
      summary: Add User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: Gaylord.Ziemann82
                name: Lillie Monahan
                email: Demetrius_Schaefer74@hotmail.com
                password: StrongPass!456
      responses:
        '201':
          description: User created successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 201
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        example: '5b2e7d18-6270-4081-a6b2-f8669d527d23'
                      username:
                        type: string
                        example: 'Gaylord.Ziemann82'
                      name:
                        type: string
                        example: 'Lillie Monahan'
                      email:
                        type: string
                        example: 'Demetrius_Schaefer74@hotmail.com'
                      created_at:
                        type: string
                        format: date-time
                        example: '2024-05-23T21:42:25.995Z'
                  message:
                    type: string
                    example: 'User created successfully.'
        '500':
          description: An error occurred while creating the User.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 500
                  error:
                    type: object
                    properties:
                      code:
                        type: string
                        example: 'USER_CREATION_ERROR'
                      message:
                        type: string
                        example: 'An error occurred while creating the user.'
  /api/auth/login:
    post:
      tags:
        - Auth
      summary: Login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: michael.brown@example.com
                password: StrongPass!456
      responses:
        '200':
          description: User logged in successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  data:
                    type: object
                    properties:
                      token:
                        type: string
                        example: 'eyJhbGciOi...'
                  message:
                    type: string
                    example: 'User logged in successfully.'
        '401':
          description: Invalid credentials.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 401
                  error:
                    type: object
                    properties:
                      code:
                        type: string
                        example: 'INVALID_CREDENTIALS'
                      message:
                        type: string
                        example: 'Invalid credentials.'
        '500':
          description: An error occurred while logging in.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 500
                  error:
                    type: object
                    properties:
                      code:
                        type: string
                        example: 'LOGIN_ERROR'
                      message:
                        type: string
                        example: 'An error occurred while logging in.'
  /api/chats:
    post:
      tags:
        - Chats
      summary: Add chat
      security:
        - bearerAuth: []
      responses:
        '201':
          description: Chat created successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 201
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        example: '5b2e7d18-6270-4081-a6b2-f8669d527d23'
                      user_id:
                        type: string
                        example: 'c2be5e6c-a186-4cf5-90d5-bad055757cc2'
                      created_at:
                        type: string
                        format: date-time
                        example: '2024-05-23T21:42:25.995Z'
                  message:
                    type: string
                    example: 'Chat created successfully.'
        '500':
          description: An error occurred while retrieving the Chats.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 500
                  error:
                    type: object
                    properties:
                      code:
                        type: string
                        example: 'CHATS_RETRIEVAL_ERROR'
                      message:
                        type: string
                        example: 'An error occurred while retrieving the Chats.'
    get:
      tags:
        - Chats
      summary: List chats
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Chats retrieved successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          example: '5b2e7d18-6270-4081-a6b2-f8669d527d23'
                        user_id:
                          type: string
                          example: 'c2be5e6c-a186-4cf5-90d5-bad055757cc2'
                        created_at:
                          type: string
                          format: date-time
                          example: '2024-05-23T21:42:25.995Z'
                  message:
                    type: string
                    example: 'Chats retrieved successfully.'
        '500':
          description: An error occurred while retrieving the Chats.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 500
                  error:
                    type: object
                    properties:
                      code:
                        type: string
                        example: 'CHATS_RETRIEVAL_ERROR'
                      message:
                        type: string
                        example: 'An error occurred while retrieving the Chats.'
    x-websocket:
      summary: WebSocket Service
      operationId: websocketService
      tags:
        - WebSocket
      parameters:
        - name: message
          in: query
          description: JSON message sent over the WebSocket connection
          required: true
          schema:
            type: object
            properties:
              type:
                type: string
                description: The type of the message. Can be 'auth' for authentication or a chat message.
              token:
                type: string
                description: The JWT token for authentication. Required if type is 'auth'.
              chatId:
                type: string
                description: The ID of the chat. Required if type is a chat message.
              content:
                type: string
                description: The content of the chat message. Required if type is a chat message.
      responses:
        '200':
          description: Successful connection
        '1008':
          description: Connection closed due to authentication error
  /api/chats/{chatId}/messages:
    post:
      tags:
        - Messages
      summary: Add message
      parameters:
        - name: chatId
          in: path
          description: The ID of the chat.
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                content: GLillie Monahan
      security:
        - bearerAuth: []
      responses:
        '201':
          description: Message created successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 201
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        example: '5b2e7d18-6270-4081-a6b2-f8669d527d23'
                      chat_id:
                        type: string
                        example: 'c2be5e6c-a186-4cf5-90d5-bad055757cc2'
                      content:
                        type: string
                        example: 'Hello, World!'
                      created_at:
                        type: string
                        format: date-time
                        example: '2024-05-23T21:42:25.995Z'
                  message:
                    type: string
                    example: 'Message created successfully.'
        '500':
          description: An error occurred while creating the Message.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 500
                  error:
                    type: object
                    properties:
                      code:
                        type: string
                        example: 'MESSAGE_CREATION_ERROR'
                      message:
                        type: string
                        example: 'An error occurred while creating the Message.'
    get:
      tags:
        - Messages
      summary: List messages
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Messages retrieved successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          example: '5b2e7d18-6270-4081-a6b2-f8669d527d23'
                        chat_id:
                          type: string
                          example: 'c2be5e6c-a186-4cf5-90d5-bad055757cc2'
                        content:
                          type: string
                          example: 'Hello, World!'
                        created_at:
                          type: string
                          format: date-time
                          example: '2024-05-23T21:42:25.995Z'
                  message:
                    type: string
                    example: 'Messages retrieved successfully.'
        '500':
          description: An error occurred while retrieving the Messages.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 500
                  error:
                    type: object
                    properties:
                      code:
                        type: string
                        example: 'MESSAGES_RETRIEVAL_ERROR'
                      message:
                        type: string
                        example: 'An error occurred while retrieving the Messages.'
